### ISSUE TITLE
Wiki creation job freezes at 75% on an instance with multiple subwikis and pro applications installed

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/application-licensing#115]
**Prerequisites:** 
1. Have Licensor API 1.21 installed on farm
2. Have multiple sub wikis (e.g. 5), each with at least a pro application installed (e.g. Diagram, Meeting Application (Pro) )

**Steps to reproduce:**
1. Create a new subwiki `test6`
2. Observe the wiki creation job progress 

**Expected result:**
After waiting for a reasonable amount of time, the wiki creation job progress displays the message `The wiki test6 has been successfully created. You can now access it.`  

**Actual result:**
Even after a long time, the wiki creation job is still running 
![wikiCreation](https://user-images.githubusercontent.com/22794181/148768208-d917907b-e431-4584-9140-7adc257c3a9f.png)
and the progress remains at 0.7499 even after 2h of waiting
```
<jobStatus xmlns="http://www.xwiki.org">
<link href="http://localhost:8081/xwiki/rest/jobstatus/wikicreation/createandinstall/test6" rel="self"/>
<id>wikicreation/createandinstall/test6</id>
<state>RUNNING</state>
<progress>
<offset>0.7499999999999989</offset>
<currentLevelOffset>0.7499999999999989</currentLevelOffset>
</progress>
<startDate>2022-01-10T14:23:08.572+02:00</startDate>
<serialized>true</serialized>
<isolated>true</isolated>
</jobStatus>
```

Note: this issue is related to #92 and can be reproduced starting with Licensing version 1.17

**Comment by gdelhumeau** [comment]
For the record, it was also breaking the upgrade of existing subwikis.
Thanks for having closed this!
