### ISSUE TITLE
Notifications are not sent when a pro application is automatically upgraded

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-licensing#120]
This issue was found on the XWiki SAS intranet, running XWiki 12.10.8 on 14/02/2022. This could be a product issue, however I did not find any relevant ticket by looking at jira.xwiki.org.

As a global admin on this instance, I have the following notification parameters : 

![image](https://user-images.githubusercontent.com/5938943/153867010-dc26f3d0-ff92-4143-9612-9b6c1f072af8.png)

However, I discovered this morning that one extension (application-xpoll) had been upgraded in a sub-wiki, without getting either a mail or a notification in the notification tray. Other notifications, such as the like of a page or a user mention work well on my account.

I'm marking this issue as a blocker as in that case, the upgrade of the extension brought a regression, and we were not able to diagnose it directly because of not being notified.

**Comment by oanalavinia** [comment]
Hi @aubincleme !
You did not received the notification because the `System Filter` is enabled.
As presented here https://github.com/xwikisas/application-licensing/issues/88#issuecomment-777341542, the notification is send by the superadmin user

**Comment by mflorea** [comment]
So this looks like an invalid issue right?

**Comment by oanalavinia** [comment]
I was waiting to see if Clement has other input before closing, but yes, it is invalid.
