### ISSUE TITLE
The Licenses section is missing on XWiki 14.10.6

### ISSUE THREAD

**Issue by gdelhumeau** [xwikisas/application-licensing#144]
<img width="679" alt="Capture d’écran 2023-03-20 à 16 49 12" src="https://user-images.githubusercontent.com/1298947/226394385-0f4eb364-a538-4307-b4c9-d0850f98fac4.png">

If I change the properties "scope" of the object "XWiki.ConfigurableClass" in "Licenses.WebHome" to "WIKI", then it appears correctly. The default value is "---", maybe it's not supported on XWiki 14.10.6?

**Comment by mflorea** [comment]
Fixed with https://github.com/xwikisas/application-licensing/commit/904a215de40b813e5afa3f99bb29c4acfda26442 .
