### ISSUE TITLE
Licensing section doesn't appear in the Administration page.

### ISSUE THREAD

**Issue by trrenty** [xwikisas/application-licensing#145]
Following the release of version 1.24, the Licensing section is not present in the Administration Page anymore. 

When the `Licenses/Code/WebHome` page was exported from an instance of XWiki v13.10, the `configureGlobally` property, being deprecated, was removed. Now, the `scope` property of the `ConfigurableClass` is empty causing the Licensing section not to be displayed. 
 
To fix this problem, we need to set the scope of the ConfigurableClass to `WIKI`. See https://www.xwiki.org/xwiki/bin/view/ReleaseNotes/Data/XWiki/13.7RC1/#HAllowtodisplayConfigurableClassinalladministrationpages

**Comment by gdelhumeau** [comment]
I have reported the same issue: https://github.com/xwikisas/application-licensing/issues/144

**Comment by trrenty** [comment]
Then I'll be closing this as duplicate.
