### ISSUE TITLE
License upscale from 25 to 250 users during active license time got created and generated with the wrong expiration date

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/application-licensing#147]
Case: active XWiki Pro license 25 users with expiration date on 27/02/2024
Need: increase to 250 users

Applied actions:
- user purchased from their instance on 10/04/2023 new XWiki Pro license 250 users

Expected expiration date: 10/04/2024
Actual expiration date: 27/02/2025

**Comment by AndreeaChi** [comment]
We also received "Order execution failure" > _An order has been successfully paid by the client, but the execution of some purchased items has failed._

Error message: https://cryptpad.fr/pad/#/2/pad/view/RkJt6LxH98gl2GnMqvRy7-j8BnGgBbCPq4mRT3tAVs8/

_java.lang.RuntimeException: Failed to generate the license. Received response is [com.xwiki.cloud.network.commons.http.HTTPResponse@30fac1fd[success=false,code=500,headers={Server=Apache, Content-Location=/xwiki/bin/view/License/Code/LicenseGenerator, Connection=close, Pragma=no-cache, Date=Mon, 10 Apr 2023 14:40:44 GMT, Strict-Transport-Security=max-age=63072000; includeSubDomains;, Cache-Control=no-cache, Set-Cookie=JSESSIONID=90D4BF60B0650FFA1D2929BAB299EED6; Path=/xwiki; Secure; HttpOnly, Expires=Wed, 31 Dec 1969 23:59:59 GMT, Content-Script-Type=text/javascript, Content-Length=0, Content-Language=en, Content-Type=text/plain;charset=UTF-8},content=]]_

**Comment by AndreeaChi** [comment]
As the license page was showing the Generate License button (also no start date, expiration date 27/02/2025), I though it was still possible to edit it and I opened it in object mode (on 10th April), added start date 10/04/2023, expiration date decided by AM with the client - 30/06/2024. 

Then I clicked on Generate License and it generated a license.

However, when the client applied it, it applied a license with the expiration date 27/02/2025.

**Comment by mflorea** [comment]
> Error message: https://cryptpad.fr/pad/#/2/pad/view/RkJt6LxH98gl2GnMqvRy7-j8BnGgBbCPq4mRT3tAVs8/

This document doesn't seem to exist anymore.

**Comment by AndreeaChi** [comment]
Hi! I'm adding a recent case with someone having the following licenses for Diagram Pro:
1. A first purchased license for 25 users with these dates 
Issue Date
29/11/2022
Expiration Date
28/01/2024
2. A second purchased license for 10 users with these dates 
Issue Date
28/12/2023
Expiration Date
16/02/2025
3. A third purchased license for 25 users with these dates
Issue Date
05/02/2024
Expiration Date
05/02/2025

As the person wants the last purchased license, they expected a conversion of time left from the 10 users license to be more than 5/02/2024. It seems that the conversion did not work for some reason, in this case.

**Comment by oanalavinia** [comment]
Closing this issue as invalid, since the XWiki Network (Shop) is the one responsible for calculating the expiration date of a license, not the licensing application itself. So this issue will be handled as part of that project
