### ISSUE TITLE
Group Restrictions on Licenses.WebHome page cause lack of access/impossibility to use Paid app to simple users

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/application-licensing#158]
It was noticed on XWiki 15.9, 14.10.15 that due to an explicit View and Modify rights given to the Licenses.WebHome page to the XWikiAdminGroup, when simple users visit a page that contains a Paid App for which there is a valid license already added, they see a rights error mentioning:

Current user [xwiki:XWiki.simpleuser] doesn't have view rights on document [subwikiname:Licenses.Code.VelocityMacros]

or 

Current user [xwiki:XWiki.simpleuser] doesn't have view rights on document [mainwiki:Licenses.Code.VelocityMacros]

Only users from the XWikiAdminGroup are able to see the that page content.

**Comment by oanalavinia** [comment]
Already fixed in https://github.com/xwikisas/application-licensing/issues/155
