### ISSUE TITLE
Clicking on “Buy” redirects to the store, with an error “There's no extension specified.”

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-licensing#162]
Environment : 
* XWiki 14.10.18 ; Jetty / HSQLDB
* PDF Viewer Macro (Pro) 2.5.3 with Licensor API 1.24.3

Steps to reproduce : 
* On a vanilla instance, install the PDF Viewer Macro Pro
* In the licensor section, fill-in the contact details (first name, last name, email)
* Click on "Buy" to get a license for the PDF Viewer

Clicking on "Buy" redirects to the store with the following error message : 

![image](https://github.com/xwikisas/application-licensing/assets/5938943/3ef9219b-af60-476c-be12-06f908be3ecc)

**Comment by mflorea** [comment]
@aubincleme it would help if you can tell us what is the URL you end up on store.xwiki.org . If it is:

    https://store.xwiki.com/xwiki/bin/view/Store/BuyLicense

then can you tell us what are the request (POST) parameters? (you can obfuscate the instance id). Most probably the extension id is not included in the submitted data. We need to understand why.

**Comment by mflorea** [comment]
I don't see what could go wrong [in the JavaScript code](https://github.com/xwikisas/application-licensing/blob/master/application-licensing-licensor/application-licensing-licensor-ui/src/main/resources/Licenses/WebHome.xml#L687-L693). Can you also inspect the "Buy" button (anchor) and copy & paste the value of the ``data-button`` attribute. Thanks.
