### ISSUE TITLE
Can not generate Diagram Pro trial license if Pro Macros is installed 

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-licensing#164]
1. Install Pro Macros 
2. In Extension Manager, search for Diagram Pro 

Issue 1: 
Two Diagram Pro results appear and the app appears as already installed
<img width="1102" alt="diagram-pro-macros" src="https://github.com/xwikisas/application-licensing/assets/35834028/08782912-f1f9-4eaf-b8ba-d8117631a7d1">

Issue 2: 
The Diagram Pro license is not visible in the License section: 
<img width="614" alt="diagram-pro-macros-2" src="https://github.com/xwikisas/application-licensing/assets/35834028/96d49601-db03-412f-b26c-9d071cf39c7a">

3. Install the latest version of Diagram Pro 
4. Go back to the license section 

Issue 3: 
The Diagram Pro still does not appear in the License section

Expected result: Diagram Pro license can be purchased individually from the Pro Macros license.

**Comment by mflorea** [comment]
@snazare this is not a bug. Pro Macros currently depends on Diagram Application, see https://github.com/xwikisas/xwiki-pro-macros/blob/main/xwiki-pro-macros-ui/pom.xml#L96 . This means:

* whoever installs Pro Macro also gets Diagram Pro installed
* when you get a license for Pro Macro is also covers the Diagram Application

> Install the latest version of Diagram Pro

You didn't install, you **upgraded** the installed Diagram Application, but that doesn't change how the licensor sees the Diagram Application.

> Diagram Pro license can be purchased individually from the Pro Macros license.

Why would you want to by a separate license when you already have license that covers it (for the Pro Macros)?

**Comment by snazare** [comment]
opening new ticket for making Diagram Pro and File Manager Pro *optional* dependencies of Pro Macros.

**Comment by snazare** [comment]
related: #168
