### ISSUE TITLE
No regex verification for License fields when getting a trial

### ISSUE THREAD

**Issue by acotiuga** [xwikisas/application-licensing#43]
It is possible to get trials for apps by only using blank spaces in the owner details inputs. We should do some minimal checks for at least 2-3 chars(non blank spaces) and an email format check.

**Comment by aubincleme** [comment]
Following 27b47e, checking for at least 4 characters in the license creation form is also a bit wrong : some users might have 3 chars long first names.

Examples : 
* Ron
* Bob
* Edy

We also have [2 letter first names](http://www.nameplayground.com/?letters=2).

**Comment by mflorea** [comment]
@aubincleme please open another issue as this one was already released. Thanks.
