### ISSUE TITLE
Provide a single entry for applications installed on main wiki and sub-wikis

### ISSUE THREAD

**Issue by evalica** [xwikisas/application-licensing#5]
Currently they are displayed in separate entries, but we should display them once and enumerate the wikis affected, see image
<img width="648" alt="single" src="https://user-images.githubusercontent.com/629552/33140517-e3eb27f6-cfb8-11e7-923c-1ce4ad1e0880.png">

**Comment by mflorea** [comment]
I can group them only if both the extension name (id) and version match, because licenses can have version constraints so we could have different licenses for different versions of an extension.
