### ISSUE TITLE
No license notification appears after installing a PRO application

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-licensing#55]
Steps to reproduce:

1. Install a PRO application - in this case used Advanced Search with Extension Id: com.xwiki.googleapps:application-googleapps
Version: 2.4-rc-5
2. Go to Home page or refresh the page

Expected results: A notification message appears to inform the user that he needs to get a license for the application. The notification bell turns red.

Actual results: No notification appears.

Environment: Windows 10, XWiki 11.2 Standard and Chrome 73 / Firefox 65 / Edge 18

![NoNotification](https://user-images.githubusercontent.com/40691112/55086214-aab58600-50b0-11e9-8445-568020225c3f.jpg)
![Installation](https://user-images.githubusercontent.com/40691112/55086215-aab58600-50b0-11e9-848c-ecfc5a9cec25.jpg)

**Comment by mflorea** [comment]
Should be fixed by the commits done for #57
