### ISSUE TITLE
Can't access the XWiki instance a second time after installing and getting a trial of a PRO application

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-licensing#56]
Steps to reproduce:

1. Install any PRO extension - in this case tried with Diagram PRO and Google Apps Integration (Pro)
2. Access Administration > Licenses and Get Trial
3. Close the XWiki instance
4. Access the instance again

Expected results: The instance opens with the installed extension.

Actual results: The instance remains stuck at 99% or 100%. User can't access it.

Environment: Windows 10, XWiki 11.2 Standard and with MySQL 5.7, using Edge 18, Chrome 73

![Stuck](https://user-images.githubusercontent.com/40691112/55092912-1e10c500-50bc-11e9-87f4-492f4b1256e4.jpg)
![Stuck2](https://user-images.githubusercontent.com/40691112/55093011-45679200-50bc-11e9-9ce0-dd3feba981f7.jpg)

**Comment by polx** [comment]
Attached is a log of a failed start with thread-dumps at the end. Several locks appear on several threads.

[console-log-of-a-startwith-stacktraces.txt](https://github.com/xwikisas/application-licensing/files/3014238/console-log-of-a-startwith-stacktraces.txt)

**Comment by polx** [comment]
One extra note: even killing the server blocks (which gives the int of a deadlock).

**Comment by mflorea** [comment]
Fixed by commits done for #57
