### ISSUE TITLE
User count fails on empty wikis

### ISSUE THREAD

**Issue by acotiuga** [xwikisas/application-licensing#64]
In an empty wiki, where the `XWiki.XWikiUsers` class doesn't exists, the query that gets the user count is wrongly converted and is warned as a broken query in the logs.

`[http://127.0.0.1:8080/xwiki/wiki/test1/admin/XWiki/XWikiPreferences?section=XWiki.Extensions&search=polls&repo=installed] WARN c.x.l.s.LicensorScriptService - Failed to count the users. Root cause is: [QueryException: could not resolve property: active of: com.xpn.xwiki.objects.BaseObject].`

**Comment by mflorea** [comment]
An option is to use HQL instead of XWQL.
