### ISSUE TITLE
The missing license is displayed when creating a new page from an extension

### ISSUE THREAD

**Issue by acotiuga** [xwikisas/application-licensing#69]
The message should not be displayed in `create` mode since there's nothing possible to go wrong with the content in this mode. They won't be able to see any template related to the current application and that's enough.

![warningMessage](https://user-images.githubusercontent.com/8121819/63938612-e55f8800-ca6d-11e9-99ed-a0104addb3e2.png)

**Comment by mflorea** [comment]
@acotiuga yes, the message should probably be limited to view action.
