### ISSUE TITLE
Pro applications have Edit right on their page and some can be used without any license after XWiki upgrade

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-licensing#72]
STEPS TO REPRODUCE
 
1. Create an older instance of XWiki (e.g. 8.4.6)
2. Install some Pro Applications on it (e.g. Forum Pro, Ideas Pro, File Manager Pro) without obtaining any (trial) license
3. Close the instance
4. Go to a newer instance (11.7) and copy/cut the
`[...]webapps\xwiki`
folder and replace it (first delete the old one) in the same location on the older version
5. Delete `solr` folder from configured permanent directory
6. Start XWiki and follow the Distribution Wizard through the upgrade process
7. On the upgraded instance, click on each app's title on Applications Panel

EXPECTED RESULTS

On each application page, a message informs the user that there is no valid License for that respective app. The user has no Edit right on the app's page.

ACTUAL RESULTS

The user has Edit right on **all** Pro applications' pages tested. 

The following apps can be fully used without obtaining any (trial) license:

- Calendar Pro
- File Manager Pro
- Forum Pro
- Ideas Pro
- Meetings Pro
- Polls Pro

However, the following apps display the message about missing license (as expected):

- Diagram Pro
- Flash Messages Pro
- Office365 Pro
- PDF Viewer Pro

The installed Licensor Api for the applications is 1.14.4.

After the upgrade, on Extensions Manager, some apps (like Meeting Pro, Calendar Pro) offer the 'Repair' option. After performing the repair, Calendar Pro displays the message about missing license, but Meeting Pro still doesn't. The Edit right is still given to the user.

Environment: Windows 10 Pro 64 bit, Chrome 77, IE11, using a local instance of XWiki 11.7 on PostgreSQL 11 and HSQL 2.5.0

Forums Pro before upgrade:
![Forums_before_upgrade](https://user-images.githubusercontent.com/32512703/65313554-378f5700-db9d-11e9-9570-c17981eb1783.jpg)

Forums Pro accessible after upgrade:
![Forums_accessible_after_upgrade (1)](https://user-images.githubusercontent.com/32512703/65313815-b2f10880-db9d-11e9-8de7-a077ca5e0833.jpg)

Licenses Page after upgrade to 11.7:
![11_7_No_License_Available](https://user-images.githubusercontent.com/32512703/65313846-c1d7bb00-db9d-11e9-87bd-b371d1111eb0.jpg)

**Comment by mflorea** [comment]
@ilieandriuta good catch, thanks!
