### ISSUE TITLE
after deletion of the recommended antivirus extension there are are messages in catalina.out about Licenses.Code.MissingLicensesUIX

### ISSUE THREAD

**Issue by matze-bech** [xwikisas/application-licensing#86]
2020-11-05 11:12:08,576 [http://************/xwiki/bin/view/Help/] ERROR o.x.v.i.DefaultVelocityEngine - Left side ($unlicensedSheets.size()) of ‘>’ operation has null value at 36:xwiki:Licenses.Code.MissingLicensesUIX^XWiki.UIExtensionClass[0][line 5, column 61]

These messages come up for every page that is visited. How can I get rid of them? Is there any cleanup routine that I can perform?

this is from XWiki 11.10 LTS running with tomcat 9 and postgresql

**Comment by mflorea** [comment]
Either there is an error logged just before, that looks like:

> Failed to get the list of associated sheets. Root cause is: [...].

that should explain the cause of your issue, or you have uninstalled the licensor API but somehow kept the ``Licenses.Code.MissingLicensesUIX`` page (provided by the licensor UI extension).

**Comment by matze-bech** [comment]
Thank You, that was very helpful indeed, with that hint we found the pages and were able to remove them, after switching the "show hidden documents", the messages are gone, thank You!
