### ISSUE TITLE
Trial license is generated for the paid apps dependencies which should be covered by the parent license.

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/application-licensing#97]
When installing a paid app, the trial license is automatically generated. If this app has as dependency another paid app (like Meeting application has XPoll application as a dependency), it's license should be covered by the parent license. The problem is that right now a new trial license is generated automatically for the paid app dependency as well.

The problem is discussed in [this](https://github.com/xwikisas/application-licensing/issues/92#issuecomment-829815012) comment as well.

**Comment by mflorea** [comment]
Maybe we should listen to "extension install job finished" rather than on ``ExtensionInstalled``, i.e. to run our code after the entire install plan was executed (all dependencies installed).
